In [1]:
import numpy as np

In [2]:
list1 = [2,3,5,6,9]
arr1 = np.array(list1)
arr1

array([2, 3, 5, 6, 9])

In [3]:
print(arr1.dtype)
print(arr1.ndim)   
print(arr1.size) 
print(arr1.shape)
print(type(arr1))

int32
1
5
(5,)
<class 'numpy.ndarray'>


In [4]:
arr1 = np.array([2,3,5,6,9], dtype=np.float32)
arr1 = np.array([2,3,5,6,9], dtype=np.int8)
arr1

array([2, 3, 5, 6, 9], dtype=int8)

In [5]:
arr1 = arr1.astype('float64')
arr1

array([2., 3., 5., 6., 9.])

__2-D Arrays__

In [6]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(arr2.ndim)
print(arr2.size) 
print(arr2.shape)
print(type(arr2))

2
6
(2, 3)
<class 'numpy.ndarray'>


__Indexing and Slicing__

In [8]:
arr1 = np.array([7, 2, 6, 3, 5, 4, 7])

In [9]:
print(arr1[2])
print(arr1[[2,3,5]])
print(arr1[1:4])
print(arr1[4:])      
print(arr1[:4])

6
[6 3 4]
[2 6 3]
[5 4 7]
[7 2 6 3]


In [10]:
print(arr1[:-2])
print(arr1[-3:-1]) 
print(arr1[::2])

[7 2 6 3 5]
[5 4]
[7 6 5 7]


In [11]:
arr2 = np.array([[1, 2, 3, 4], [7, 7, 8, 8], [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 7,  7,  8,  8],
       [ 9, 10, 11, 12]])

In [12]:
print(arr2[1])
print(arr2[1][1])
print(arr2[1,1])

[7 7 8 8]
7
7


In [13]:
print(arr2[0:2])
print(arr2[1:])      
print(arr2[:2])

[[1 2 3 4]
 [7 7 8 8]]
[[ 7  7  8  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [7 7 8 8]]


In [14]:
arr2[2] = 55
arr2

array([[ 1,  2,  3,  4],
       [ 7,  7,  8,  8],
       [55, 55, 55, 55]])

In [15]:
print(arr2[-3:-1])
print(arr2[::2])

[[1 2 3 4]
 [7 7 8 8]]
[[ 1  2  3  4]
 [55 55 55 55]]


In [16]:
arr3 = np.array([[[1, 2, 3, 4], [7, 2, 6, 7]],
                 [[9, 10, 11, 12], [7, 7, 8, 8]],
                 [[1, 2, 3, 4], [9, 10, 11, 12]]])

In [17]:
print(arr3[0:1])
print(arr3[1:]) 

[[[1 2 3 4]
  [7 2 6 7]]]
[[[ 9 10 11 12]
  [ 7  7  8  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]


In [18]:
arr3[1:, 0:1]

array([[[ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4]]])

In [19]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [20]:
a[a < 7]

array([1, 2, 3, 4, 5, 6])

In [21]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [22]:
np.nonzero(a < 7)

(array([0, 0, 0, 0, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 0, 1], dtype=int64))

__Sorting__

In [23]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

__Statistics__

In [24]:
arr1.mean()

4.857142857142857

In [25]:
arr1.std()

1.8070158058105024

In [26]:
arr2.sum()

260

In [27]:
arr2.mean()

21.666666666666668

In [28]:
arr2.mean(axis=0)

array([21.        , 21.33333333, 22.        , 22.33333333])

In [29]:
arr2.std(axis=0)

array([24.16609195, 23.89328125, 23.42363479, 23.15647258])

__Array Creation__

In [30]:
arr_0s = np.zeros(5)
arr_0s

array([0., 0., 0., 0., 0.])

In [31]:
arr_0s.dtype

dtype('float64')

In [32]:
arr_0s = np.zeros((5), dtype = np.int32) 
arr_0s

array([0, 0, 0, 0, 0])

In [33]:
arr_1s = np.ones(5) 
arr_1s

array([1., 1., 1., 1., 1.])

In [34]:
arr_1s = np.ones((5), dtype=bool) 
arr_1s

array([ True,  True,  True,  True,  True])

In [35]:
arr_1s = np.ones((2,3))
arr_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
arr_i = np.eye(3)
arr_i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
arr_1sl = np.ones_like(arr_i)
arr_1sl

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.empty((4,4))

array([[4.67296746e-307, 1.69121096e-306, 1.69118787e-306,
        8.34441742e-308],
       [1.78022342e-306, 6.23058028e-307, 9.79107872e-307,
        6.89807188e-307],
       [7.56594375e-307, 6.23060065e-307, 1.78021527e-306,
        8.34454050e-308],
       [1.11261027e-306, 1.15706896e-306, 1.33512173e-306,
        1.33504432e-306]])

In [39]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [40]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [42]:
a = np.arange(5)
a+10

array([10, 11, 12, 13, 14])

In [43]:
np.arange(15, 8, -1)  

array([15, 14, 13, 12, 11, 10,  9])

In [44]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

__Random sampling__

In [45]:
np.random.rand(4)

array([0.36307709, 0.35614747, 0.71182067, 0.98181306])

In [46]:
np.random.rand(3,2)

array([[0.48872889, 0.00930678],
       [0.44821115, 0.32832962],
       [0.20668732, 0.08216685]])

In [47]:
np.random.randint(6, size=5)

array([1, 1, 2, 3, 0])

In [48]:
np.random.random((5, 3))

array([[0.70654644, 0.17206764, 0.16951709],
       [0.01155936, 0.55458618, 0.04863073],
       [0.04489261, 0.43040653, 0.38244931],
       [0.49767995, 0.92573538, 0.34511265],
       [0.33841028, 0.13107741, 0.82786631]])

__Mask/Filtering__

In [49]:
arr = np.array([7, 2, 6, 3, 5])
arr >= 3

array([ True, False,  True,  True,  True])

In [50]:
arr[arr >= 3]

array([7, 6, 3, 5])

In [51]:
arr[arr%2 == 0]

array([2, 6])

In [52]:
arr[arr>arr.mean()]

array([7, 6, 5])

In [53]:
arr[(arr<3) | (arr>5)]

array([7, 2, 6])

In [54]:
np.where(arr < 5, arr, 10*arr)

array([70,  2, 60,  3, 50])

__Array operations__

In [55]:
a1 = np.array([1, 2, 5])
a2 = np.ones(3, dtype=int)

In [56]:
a1 + a2

array([2, 3, 6])

In [57]:
a1 * a1

array([ 1,  4, 25])

In [58]:
a1 * 1.2

array([1.2, 2.4, 6. ])

In [59]:
a1.sum()

8

In [60]:
a1.max()

5

In [61]:
arr1 = np.arange(0,9).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)

In [62]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
arr1.sum(axis=0)

array([ 9, 12, 15])

In [64]:
arr1.sum(axis=1)

array([ 3, 12, 21])

In [65]:
arr1.max(axis=0)

array([6, 7, 8])

In [66]:
np.add(arr1,arr2)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [67]:
np.multiply(arr1,arr2)

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [68]:
np.matmul(arr1,arr2)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [69]:
a1 = np.arange(0,3)
a2 = np.arange(2,5)
np.dot(a1, a2)

11

__Transpose__

In [70]:
arr2 = np.array([[1, 4, 5], [2, 6, 7]])
np.transpose(arr2)

array([[1, 2],
       [4, 6],
       [5, 7]])

In [71]:
arr2.T

array([[1, 2],
       [4, 6],
       [5, 7]])

__Reverse__

In [72]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [73]:
np.flip(arr2)

array([[7, 6, 2],
       [5, 4, 1]])

__Array Reshaping__

In [74]:
a1 = np.arange(0,6)
a1

array([0, 1, 2, 3, 4, 5])

In [75]:
a1.reshape(2,3) 

array([[0, 1, 2],
       [3, 4, 5]])

In [76]:
a1.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [77]:
np.arange(1,11).reshape(2,5) 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [78]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [79]:
arr2.ravel() 

array([1, 4, 5, 2, 6, 7])

In [80]:
arr2.flatten()

array([1, 4, 5, 2, 6, 7])

__Array Join__

In [81]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [82]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
np.concatenate((arr1, arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [83]:
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

__Stack Arrays__

In [84]:
arr1 = np.arange(0,4).reshape(2,2)
arr2 = np.arange(8,12).reshape(2,2)
np.vstack((arr1, arr2))

array([[ 0,  1],
       [ 2,  3],
       [ 8,  9],
       [10, 11]])

In [85]:
np.hstack((arr1, arr2))

array([[ 0,  1,  8,  9],
       [ 2,  3, 10, 11]])

In [86]:
np.column_stack((arr1, arr2))

array([[ 0,  1,  8,  9],
       [ 2,  3, 10, 11]])

__Array Splitting__

In [87]:
arr1 = np.arange(0,6)
np.array_split(arr1, 2)

[array([0, 1, 2]), array([3, 4, 5])]

In [88]:
arr1 = np.arange(0,7)
np.array_split(arr1, 3)

[array([0, 1, 2]), array([3, 4]), array([5, 6])]

In [89]:
arr2 = np.arange(9).reshape(3,3) 
np.array_split(arr1, 2)

[array([0, 1, 2, 3]), array([4, 5, 6])]

In [90]:
arr2 = np.arange(0,8).reshape(2,4) 
np.hsplit(arr2, 2)

[array([[0, 1],
        [4, 5]]),
 array([[2, 3],
        [6, 7]])]

In [91]:
arr2 = np.arange(0,8).reshape(2,4) 
np.vsplit(arr2, 2)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]])]

__Counter objects__

In [92]:
from collections import Counter
class1 = ["Bob", "James", "Chad", "Darcy", "Penny", "Hannah", "Kevin", "James", "Melanie", "Becky", "Steve", "Frank"]
class2 = ["Bill", "Barry", "Cindy", "Debbie", "Frank", "Gabby", "Kelly", "James", "Joe", "Sam", "Tara", "Ziggy"]

In [93]:
c1 = Counter(class1)
c1

Counter({'Bob': 1,
         'James': 2,
         'Chad': 1,
         'Darcy': 1,
         'Penny': 1,
         'Hannah': 1,
         'Kevin': 1,
         'Melanie': 1,
         'Becky': 1,
         'Steve': 1,
         'Frank': 1})

In [94]:
c1.most_common(3)

[('James', 2), ('Bob', 1), ('Chad', 1)]

In [95]:
Counter(class1) & Counter(class2)

Counter({'James': 1, 'Frank': 1})